<?php

if (! defined('ABSPATH')) {
    exit;
}

// ============================================================
// AUTO-EXPORT ON SAVE — keep polyglot-flat/ in sync (LOCAL DEV ONLY)
// ============================================================
//
// Gutenberg / classic edits write straight to the DB; the flat files are
// otherwise only regenerated by `wp polyglot export`. This module closes that
// gap locally: after a translatable post is saved, it spawns a detached
// `wp polyglot export --worker` so polyglot-flat/ reflects the new DB state.
//
// Queue / concurrency (handled in the worker, inc/cli.php::export_worker_drain):
//   - a MySQL named lock guarantees a single export runs at a time;
//   - a save landing mid-export re-arms 'polyglot_export_pending' so exactly
//     one trailing export runs afterwards (no lost edits).
//
// Safety: disabled on production (gated on a 127.0.0.1 WP_HOME, which prod
// never has) and never fires inside WP-CLI (imports/translate write posts too).
// Force on/off with the POLYGLOT_AUTOEXPORT constant; point at a specific
// wp binary with POLYGLOT_WP_BIN.

/**
 * Whether auto-export is active in this environment.
 */
function polyglot_autoexport_enabled(): bool
{
    if (defined('POLYGLOT_AUTOEXPORT')) {
        return (bool) POLYGLOT_AUTOEXPORT;
    }

    // Local dev only: wp-config sets WP_HOME to http://127.0.0.1:<port> locally;
    // production WP_HOME is the real domain, so this can never be true on prod.
    $home = defined('WP_HOME') ? WP_HOME : home_url();

    return 1 === preg_match('#://(?:127\.0\.0\.1|localhost)(?::|/|$)#', (string) $home);
}

add_action('wp_after_insert_post', 'polyglot_autoexport_on_save', 999, 4);

/**
 * Arm the export queue and kick a background worker after a content save.
 */
function polyglot_autoexport_on_save($post_id, $post, $update, $post_before): void
{
    // Never recurse from CLI (import / translate write posts in WP-CLI context).
    if (defined('WP_CLI') && WP_CLI) {
        return;
    }
    if (wp_is_post_autosave($post_id) || wp_is_post_revision($post_id)) {
        return;
    }
    if (! polyglot_autoexport_enabled()) {
        return;
    }
    if (! ($post instanceof WP_Post) || ! in_array($post->post_type, polyglot_get_post_types(), true)) {
        return;
    }
    // Mirror the same statuses the export ships (publish + drafts), so editing
    // an unpublished post keeps its flat file current. Skips auto-draft / trash.
    if (! in_array($post->post_status, polyglot_exportable_statuses(), true)) {
        return;
    }

    // Arm the queue: the worker reads & clears this flag, looping once more if a
    // save sets it again mid-export. Correctness lives here, not in the debounce.
    set_transient('polyglot_export_pending', time(), 10 * MINUTE_IN_SECONDS);

    polyglot_autoexport_spawn_worker();
}

add_action('trashed_post', 'polyglot_autoexport_on_delete', 999);
add_action('untrashed_post', 'polyglot_autoexport_on_delete', 999);
add_action('deleted_post', 'polyglot_autoexport_on_delete', 999, 2);

/**
 * Arm the export queue when a translatable post is trashed, restored or
 * permanently deleted. The export then purges the orphaned flat folder
 * (run_export_core) so polyglot-flat/ never keeps content the DB has dropped.
 *
 * `trashed_post`/`untrashed_post` pass the previous status as 2nd arg, while
 * `deleted_post` passes the (already removed) WP_Post — hence the WP_Post check
 * with a get_post() fallback for the trash/restore path.
 *
 * @param int               $post_id
 * @param WP_Post|string|null $post  WP_Post on deleted_post, previous status otherwise.
 */
function polyglot_autoexport_on_delete($post_id, $post = null): void
{
    if (defined('WP_CLI') && WP_CLI) {
        return;
    }
    if (! polyglot_autoexport_enabled()) {
        return;
    }

    $post = $post instanceof WP_Post ? $post : get_post($post_id);
    if (! ($post instanceof WP_Post) || ! in_array($post->post_type, polyglot_get_post_types(), true)) {
        return;
    }

    set_transient('polyglot_export_pending', time(), 10 * MINUTE_IN_SECONDS);

    polyglot_autoexport_spawn_worker();
}

/**
 * Spawn a detached `wp polyglot export --worker`. Non-blocking: the editor
 * request returns immediately and the export runs in a separate process.
 */
function polyglot_autoexport_spawn_worker(): void
{
    if (! function_exists('exec')) {
        return;
    }

    // Light debounce so a burst of saves doesn't fork a worker each time. This
    // is an optimisation only — the pending flag + drain loop guarantee a save
    // is never dropped even when no fresh worker is spawned here.
    if (get_transient('polyglot_export_spawn_guard')) {
        return;
    }
    set_transient('polyglot_export_spawn_guard', 1, 3);

    $abspath = rtrim(ABSPATH, '/\\');
    $wp = defined('POLYGLOT_WP_BIN') ? POLYGLOT_WP_BIN : $abspath.'/wp';

    // cd into ABSPATH so wp.phar finds wp-config; nohup + & detaches the process.
    $cmd = sprintf(
        'cd %s && nohup %s polyglot export --worker > /dev/null 2>&1 &',
        escapeshellarg($abspath),
        escapeshellarg($wp)
    );

    exec($cmd);
}
